<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <ProjectReference Include="..\..\src\OpenKustoExplorer.Infrastructure\OpenKustoExplorer.Infrastructure.csproj" />
  </ItemGroup>
</Project>